services:
  - type: web
    name: playlist-site
    env: node
    buildCommand: rm -rf node_modules package-lock.json && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 