services:
  - type: web
    name: playlist-site
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true 